package com.raglaw.memory.context;

public enum ContextSectionType {
    GOVERNANCE, ROLE_CONTRACT, CURRENT_TASK, CASE_FACTS, DISPUTED_FACTS,
    TASK_NOTE, DEPENDENCY_RESULT, EVIDENCE, LEGAL_AUTHORITY,
    RECENT_CONVERSATION, HISTORY_RECALL, TOOL_ARTIFACT
}
